note: 比赛场地采集布局 (tools/make_arena_layout.py 从 competition_arena.world 导出)
world: /home/ubuntu/AiC-2026/src/competition_arena/worlds/competition_arena.world
objects:
- cls: standee
  name: A_north_1
  model: standee_c01
  x: -1.142
  y: 1.208
  yaw: -1.5708
- cls: standee
  name: A_north_2
  model: standee_c02
  x: -1.052
  y: 1.208
  yaw: -1.5708
- cls: standee
  name: A_north_3
  model: standee_c03
  x: -0.962
  y: 1.208
  yaw: -1.5708
- cls: standee
  name: A_north_4
  model: standee_c04
  x: -0.872
  y: 1.208
  yaw: -1.5708
- cls: standee
  name: A_north_5
  model: standee_c05
  x: -0.782
  y: 1.208
  yaw: -1.5708
- cls: standee
  name: A_south_1
  model: standee_c06
  x: -1.097
  y: 1.107
  yaw: 1.5708
- cls: standee
  name: A_south_2
  model: standee_c07
  x: -1.007
  y: 1.107
  yaw: 1.5708
- cls: standee
  name: A_south_3
  model: standee_c08
  x: -0.917
  y: 1.107
  yaw: 1.5708
- cls: standee
  name: A_south_4
  model: standee_c09
  x: -0.827
  y: 1.107
  yaw: 1.5708
- cls: non_community
  name: A_west_1
  model: standee_F1
  x: -1.212
  y: 1.1575
  yaw: 0.0
- cls: standee
  name: B_north_1
  model: standee_c10
  x: -1.076
  y: -0.103
  yaw: -1.5708
- cls: standee
  name: B_north_2
  model: standee_c11
  x: -0.986
  y: -0.103
  yaw: -1.5708
- cls: standee
  name: B_north_3
  model: standee_c12
  x: -0.896
  y: -0.103
  yaw: -1.5708
- cls: standee
  name: B_north_4
  model: standee_c13
  x: -0.806
  y: -0.103
  yaw: -1.5708
- cls: standee
  name: B_east_1
  model: standee_c14
  x: -0.707
  y: -0.215
  yaw: 3.1416
- cls: non_community
  name: B_east_2
  model: standee_F2
  x: -0.707
  y: -0.125
  yaw: 3.1416
- cls: traffic_light
  name: tl_top
  model: traffic_light_h
  x: -0.506
  y: 1.779
  yaw: 0.0
- cls: traffic_light
  name: tl_bot
  model: traffic_light_h
  x: -0.11
  y: -1.28
  yaw: 1.5708
- cls: plate
  name: car_1_p
  model: car_1
  x: 2.056
  y: -0.501
  yaw: 3.1416
- cls: plate
  name: car_2_p
  model: car_2
  x: 2.056
  y: -1.1245
  yaw: 3.1416
- cls: plate
  name: car_3_p
  model: car_3
  x: 2.056
  y: -1.762
  yaw: 3.1416
