#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""生成**采集专用世界** —— 只放小车 + 要识别的东西，按"工位"分成三块。

设计（2026-09-23 按需求定）
---------------------------
    工位 A  立牌圈:  10 个立牌 (社区 c01..c08 + 非社区 F1/F2) 围成一圈,
                     每个立牌 **yaw = 它的方位角** -> 正面**全部朝圈心**。
                     小车在圈心原地转, 所以每一张拍到的都是正面 (不会拍到背板)。
    工位 B  红绿灯:  2 个灯 (名字仍是 tl_top/tl_bot, 这样切换节点照常认它们),
                     正面朝外摆一排; 小车在固定距离范围正对着拍, 三种灯态都拍。
    工位 C  车牌:    3 辆车摆一排, 车牌朝外; 小车同样正对着拍。

为什么要单独建世界: 现有比赛场地里立牌是贴着街区边线摆的, 车只能在车道上,
**绕不到目标侧面**, 而采集需要多角度。这里没有围墙/街区, 车可以随便传送。

场地铺 3x3 的 `arena_floor` 贴图 (13.2 x 13.2 m), 保持和比赛场地**同样的观感**
(黑底 + 白线), 减少训练/部署的域差。

产出
----
    src/competition_arena/worlds/collect.world            世界文件
    src/competition_arena/config/collect_layout.yaml      物体清单 (采集脚本读它)

用法
----
    python3 tools/build_collect_world.py
    roslaunch competition_robot robot_gazebo.launch \\
        world:=$(rospack find competition_arena)/worlds/collect.world x:=0 y:=0 yaw:=0
"""
from __future__ import annotations

import argparse
import math
import os

import yaml

WS = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ARENA = os.path.join(WS, 'src', 'competition_arena')

# ---- 工位 A: 立牌圈 ----
# 圈半径 (m)。★ 注意"拍摄距离"不是这个半径: 相机在车心**前方 0.149m**, 车还会
#   在圈心附近随机偏移 (--ring-offset), 所以 相机到立牌 = 半径 - 偏移 - 0.149。
#   要落在比赛那个 0.50~0.55m 的量级、且立牌下沿不出画 (d>=0.48), 取 0.80:
#     相机距离 ≈ 0.80 - 0.15 - 0.149 = 0.50 ~ 0.80 m ✓
RING_R = 0.80
RING_MODELS = ['standee_c01', 'standee_c02', 'standee_c03', 'standee_c04',
               'standee_c05', 'standee_c06', 'standee_c07', 'standee_c08',
               'standee_F1', 'standee_F2']
# ---- 工位 B: 红绿灯 (正面朝 +x, 车从 +x 侧对着拍) ----
LIGHT_X, LIGHT_YS = -3.00, [2.05, 0.85]
LIGHT_NAMES = ['tl_top', 'tl_bot']
# ---- 工位 C: 车牌 (车头/车牌朝 +x, 车从 +x 侧对着拍) ----
CAR_X, CAR_YS = 3.00, [-1.10, 0.10, 1.30]
# ★ 车牌朝哪边: 车牌在车体局部 **+x** 面, 采集车又放在 +x 侧, 所以这里必须 yaw=0
#   (最初抄了比赛 world 的 3.1416, 结果车牌朝 -x, 拍到的全是车尾 —— 例图里没车牌 ✗)
CAR_YAW = 0.0
FLOOR_TILE = 4.4           # arena_floor 单块尺寸
FLOOR_N = 3                # 3x3 铺满 -> 13.2 x 13.2

# ---- 采集用的"相机小车" (rig): 只装相机, 参数与真车完全一致 ----
#   为什么要 rig 而不是三个完整机器人: 相机插件的话题名是写死的, 多实例必须各自
#   命名空间; 而 rig 是**各自独立的模型文件**, 每台一个 robotNamespace 就解决了。
#   采集流程本来就只"传送"不"驱动", 所以不需要驱动插件/里程计 —— 位姿直接从
#   /gazebo/get_model_state 读。
RIGS = [dict(name='collect_rig_1', ns='rig1', x=0.0, y=0.0, yaw=0.0),    # 圈心
        dict(name='collect_rig_2', ns='rig2', x=-1.0, y=1.45, yaw=0.0),  # 拍灯
        dict(name='collect_rig_3', ns='rig3', x=4.2, y=0.10, yaw=math.pi)]  # 拍车牌

RIG_SDF = """<?xml version="1.0"?>
<!-- 采集用相机小车 (auto-generated by tools/build_collect_world.py)
     相机参数与 competition_robot 完全一致: 1280x960 / HFOV 58 / 离地 0.19998 /
     clip 0.05~20 / 距车心 0.14914 前。话题: /{ns}/camera/rgb/image_raw
     动态但**关重力**: 传送后不会掉、且渲染会跟随 (静态模型挪了不重绘)。 -->
<sdf version="1.6">
  <model name="{name}">
    <static>false</static>
    <link name="link">
      <gravity>false</gravity>
      <inertial><mass>0.5</mass>
        <inertia><ixx>0.01</ixx><ixy>0</ixy><ixz>0</ixz>
                 <iyy>0.01</iyy><iyz>0</iyz><izz>0.01</izz></inertia></inertial>
      <visual name="cam_body">
        <pose>0 0 0.10 0 0 0</pose>
        <geometry><box><size>0.12 0.12 0.20</size></box></geometry>
        <material><ambient>0.6 0.6 0.65 1</ambient><diffuse>0.7 0.7 0.75 1</diffuse>
        </material>
      </visual>
      <sensor name="camera" type="camera">
        <always_on>true</always_on>
        <update_rate>15</update_rate>
        <visualize>false</visualize>
        <camera>
          <horizontal_fov>1.012291</horizontal_fov>
          <image><width>1280</width><height>960</height><format>R8G8B8</format></image>
          <clip><near>0.05</near><far>20</far></clip>
        </camera>
        <plugin name="camera_plugin" filename="libgazebo_ros_camera.so">
          <robotNamespace>/{ns}</robotNamespace>
          <cameraName>camera</cameraName>
          <frameName>camera_link</frameName>
          <imageTopicName>rgb/image_raw</imageTopicName>
          <cameraInfoTopicName>rgb/camera_info</cameraInfoTopicName>
        </plugin>
      </sensor>
    </link>
  </model>
</sdf>
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--ring-radius', type=float, default=RING_R)
    ap.add_argument('--models', default=','.join(RING_MODELS))
    ap.add_argument('--out-world', default=os.path.join(ARENA, 'worlds', 'collect.world'))
    ap.add_argument('--out-layout', default=os.path.join(ARENA, 'config', 'collect_layout.yaml'))
    a = ap.parse_args()

    models = [m.strip() for m in a.models.split(',') if m.strip()]
    n = len(models)
    objects = []

    parts = ['<?xml version="1.0" ?>',
             '<!--',
             '  采集专用世界 (auto-generated by tools/build_collect_world.py)',
             '',
             '  工位 A 立牌圈: 10 个立牌围成圈, 正面全部朝圈心, 小车在圈心转圈拍',
             '  工位 B 红绿灯: 2 个灯正面朝 +x 摆一排, 车从 +x 侧固定距离正对拍',
             '  工位 C 车牌:   3 辆车车牌朝 +x 摆一排, 车从 +x 侧固定距离正对拍',
             '-->',
             '<sdf version="1.6">',
             '  <world name="collect">',
             '',
             '    <!-- 物理步进: 与比赛场地保持一致 (见 build_arena.py / issue #5) -->',
             '    <physics name="collect_physics" default="0" type="ode">',
             '      <max_step_size>0.002</max_step_size>',
             '      <real_time_factor>1.0</real_time_factor>',
             '      <real_time_update_rate>500</real_time_update_rate>',
             '      <ode><solver><type>quick</type><iters>50</iters><sor>1.3</sor>',
             '      </solver></ode>',
             '    </physics>',
             '',
             '    <include><uri>model://sun</uri></include>',
             '',
             '    <!-- ================= 地面: 3x3 平铺, 与比赛场地同观感 ============ -->']
    # ★ arena_floor 在比赛 world 里是**内联**的模型 (不是 model:// 独立模型),
    #   所以这里也内联; 材质用 file://media/... 由 GAZEBO_RESOURCE_PATH 解析
    #   (launch 里已把 competition_arena 加进去)。
    FLOOR_TMPL = '''    <model name="floor_{i}_{j}">
          <static>true</static>
          <pose>{x:.3f} {y:.3f} -0.0100 0 0 0</pose>
          <link name="link">
            <collision name="collision">
              <geometry><box><size>{sz} {sz} 0.0200</size></box></geometry>
              <surface><friction><ode><mu>1.0</mu><mu2>1.0</mu2></ode></friction>
                <contact><ode><kp>1e10</kp><kd>1</kd></ode></contact></surface>
            </collision>
            <visual name="visual">
              <geometry><box><size>{sz} {sz} 0.0200</size></box></geometry>
              <material><script>
                <uri>file://media/materials/scripts/arena.material</uri>
                <name>Arena/Floor</name>
              </script></material>
            </visual>
          </link>
        </model>'''
    half = FLOOR_N // 2
    for i in range(-half, half + 1):
        for j in range(-half, half + 1):
            nm = 'floor_%d_%d' % (i + half, j + half)
            parts.append(FLOOR_TMPL.format(i=i + half, j=j + half, x=i * FLOOR_TILE,
                                           y=j * FLOOR_TILE, sz=FLOOR_TILE))
            # floor 不进 objects (没有 'pts', 采集脚本也不需要它)

    # ---- 采集用相机小车 (rig) ----
    os.makedirs(os.path.join(ARENA, 'models'), exist_ok=True)
    for r in RIGS:
        d = os.path.join(ARENA, 'models', r['name'])
        os.makedirs(d, exist_ok=True)
        open(os.path.join(d, 'model.sdf'), 'w').write(
            RIG_SDF.format(name=r['name'], ns=r['ns']))
        open(os.path.join(d, 'model.config'), 'w').write(
            '<?xml version="1.0"?>\n<model>\n  <name>%s</name>\n  <version>1.0</version>\n'
            '  <sdf version="1.6">model.sdf</sdf>\n'
            '  <description>采集用相机小车 (%s)</description>\n</model>\n'
            % (r['name'], r['ns']))
        parts.append('    <include><uri>model://%s</uri><name>%s</name>'
                     '<pose>%.3f %.3f 0 0 0 %.6f</pose></include>'
                     % (r['name'], r['name'], r['x'], r['y'], r['yaw']))

    # ---- 工位 A: 立牌圈 (正面朝圈心: 立牌正面 = 模型局部 -x, 所以 yaw = 方位角) ----
    parts += ['', '    <!-- ================= A 立牌圈 (正面全部朝圈心) ================= -->']
    for k, m in enumerate(models):
        th = 2 * math.pi * k / n
        x, y = a.ring_radius * math.cos(th), a.ring_radius * math.sin(th)
        parts.append('    <include><uri>model://%s</uri>'
                     '<name>ring_%02d</name>'
                     '<pose>%.4f %.4f 0 0 0 %.6f</pose></include>'
                     % (m, k + 1, x, y, th))
        objects.append(dict(cls='non_community' if '_F' in m else 'standee',
                            name='ring_%02d' % (k + 1), model=m,
                            x=x, y=y, yaw=th, ring=True))

    # ---- 工位 B: 红绿灯 ----
    parts += ['', '    <!-- ================= B 红绿灯 (正面朝 +x) ==================== -->']
    for nm, ly in zip(LIGHT_NAMES, LIGHT_YS):
        parts.append('    <include><uri>model://traffic_light_h</uri>'
                     '<name>%s</name><pose>%.3f %.3f 0.002 0 0 0</pose></include>'
                     % (nm, LIGHT_X, ly))
        objects.append(dict(cls='traffic_light', name=nm, model='traffic_light_h',
                            x=LIGHT_X, y=ly, yaw=0.0))

    # ---- 工位 C: 车牌 ----
    parts += ['', '    <!-- ================= C 车牌 (车牌朝 +x) ====================== -->']
    for k, cy in enumerate(CAR_YS):
        parts.append('    <include><uri>model://car_%d</uri>'
                     '<name>car_%d</name>'
                     '<pose>%.3f %.3f 0 0 0 %.6f</pose></include>'
                     % (k + 1, k + 1, CAR_X, cy, CAR_YAW))
        objects.append(dict(cls='plate', name='car_%d' % (k + 1), model='car_%d' % (k + 1),
                            x=CAR_X, y=cy, yaw=CAR_YAW))
    parts += ['', '  </world>', '</sdf>', '']

    os.makedirs(os.path.dirname(a.out_world), exist_ok=True)
    open(a.out_world, 'w').write('\n'.join(parts))

    layout = dict(
        rigs=[dict(name=r['name'], ns=r['ns'], camera_topic='/%s/camera/rgb/image_raw' % r['ns'])
              for r in RIGS],
        note='采集专用世界布局 (tools/build_collect_world.py 生成); '
             'gen_collect_dataset.py 读它来规划拍摄位姿',
        world=a.out_world,
        ring=dict(radius=a.ring_radius, n=n, center=[0.0, 0.0],
                  models=models),
        objects=objects,
    )
    with open(a.out_layout, 'w') as f:
        f.write('# 采集专用世界的物体清单 (唯一真值源)\n')
        yaml.safe_dump(layout, f, allow_unicode=True, sort_keys=False)

    print('写出:')
    print('  %s  (%d 个 include)' % (a.out_world, len(objects)))
    print('  %s' % a.out_layout)
    print()
    print('  工位 A 立牌圈: %d 个立牌, 半径 %.2f m (弧间距 %.2f m, 每张正面朝圈心)'
          % (n, a.ring_radius, 2 * math.pi * a.ring_radius / n))
    print('  工位 B 红绿灯: %d 个, x=%.2f" 正面朝 +x' % (len(LIGHT_YS), LIGHT_X))
    print('  工位 C 车牌:   %d 辆, x=%.2f, 车牌朝 +x' % (len(CAR_YS), CAR_X))
    print('  相机小车 rig:  %d 台 -> %s' % (len(RIGS),
          ', '.join('/%s/camera/rgb/image_raw' % r['ns'] for r in RIGS)))
    print()
    print('跑法:')
    print('  roslaunch competition_robot robot_gazebo.launch \\')
    print('      world:=%s x:=0 y:=0 yaw:=0' % a.out_world)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
